<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SoapCore" Version="1.2.1.14" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TradeServices">
      <HintPath>..\TradeServices\bin\Debug\net9.0-windows\TradeServices.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
